// All applicable spells as of Eldritch Moon
// Search query: o:"counter target spell" t:instant ci:u -o:unless -o:"additional cost" not:funny
module.exports = [
	'Arcane Denial',
	'Assert Authority',
	'Broken Concentration',
	'Cancel',
	// 'Confirm Suspicions',
	'Contradict',
	'Controvert',
	'Counterbore',
	'Counterlash',
	'Countermand',
	'Counterspell',
	'Cryptic Command',
	// 'Desertion',
	'Discombobulate',
	'Dismal Failure',
	'Dismiss',
	'Disrupting Shoal',
	'Dissipate',
	'Dissolve',
	'Dream Fracture',
	'Fervent Denial',
	'Foil',
	'Fold into Æther',
	'Forbid',
	'Force of Will',
	// 'Fuel for the Cause',
	'Hinder',
	'Last Word',
	// 'Lay Bare',
	'Lost in the Mist',
	'Mana Drain',
	'Memory Lapse',
	'Minamo\'s Meddling',
	'Overwhelming Denial',
	'Pact of Negation',
	'Put Away',
	'Remand',
	'Rewind',
	'Scatter to the Winds',
	'Scattering Stroke',
	'Spell Blast',
	'Spell Burst',
	'Spell Crumple',
	'Spelljack',
	'Statute of Denial',
	'Stoic Rebuttal',
	'Thwart',
	'Traumatic Visions',
	'Vex',
	'Void Shatter',
];
